# Generated by Django 3.1.2 on 2020-10-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201019_1246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
