# Generated by Django 3.1.2 on 2020-10-26 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201026_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_number',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.maingroup'),
        ),
    ]
