# Generated by Django 3.1.2 on 2020-10-26 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201026_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maingroup',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maingroup',
            name='description',
            field=models.TextField(blank=True, verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='maingroup',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'level 1'), (2, 'level 2'), (3, 'level 3'), (4, 'level 4')], null=True),
        ),
    ]
