# Generated by Django 3.1.2 on 2020-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
